### ISSUE TITLE
posixtime.m returns error when using MATLAB

### ISSUE THREAD

**Issue by clayton33** [socib/glider_toolbox#4]
When using the generateOutputNetCDF.m  an error is returned immediately when it calls posixtime.m with the error statement 'Missing required mex file'. Looking in posixtime, there appears to be no code to be ran when using MATLAB (lines 55 and 56 of current version on github), only octave. I've noticed that there is a function called setupMexPosixtime.m to create the mex file, I've used it and have successfully created the mex file.

Any suggestions as how to move forward to create a netCDF file ?

**Comment by cyrf0006** [comment]
Try to run (in Matlab):
>> setupMexPosixtime()

**Comment by cyrf0006** [comment]
I thought executing `setupMexPosixtime` would solve the problem.

Have you checked that the function is in your path? e.g.,
`>>  which posixtime()
`

**Comment by clayton33** [comment]
The function is in my path.

This is the code provided in the current version on github (see below). How I'm understanding it is that if I'm not running in octave, the function does not do anything, and I'll get an error. I am running on windows, and I don't believe that I have octave on the machine that I'm using, so I'm guessing that could be the issue ?

`  error(nargchk(0, 0, nargin, 'struct'));

  % Consider making the variable persistent
  % (the needed emptiness check may be more expensive than the existence check).
  ISOCTAVE = exist('OCTAVE_VERSION','builtin');

  if ISOCTAVE
    t = time();
  else
    error('glider_toolbox:posixtime:MissingMexFile', ...
          'Missing required mex file.');
  end

end`

**Comment by cyrf0006** [comment]
Actually, I had the same problem when I first started with the toolbox, but compiling `setupMexPosixtime` fixed the problem. The problem is discussed [here](https://github.com/socib/glider_toolbox/pull/3) (check 2nd comment on March 7). As discussed there, a local workaround can be used, but should not be a permanent solution. Maybe the problem is with your C compiler?

If you want to try the workaround, replace
```
-  else
-    error('glider_toolbox:posixtime:MissingMexFile', ...
-          'Missing required mex file.');
```
with
```
+  else 
+      t = (now()-datenum(1970,1,1))*86400;
```

Maybe @joanpau has an idea on why setupMex is not working...

**Comment by clayton33** [comment]
Thanks, I'll try that.

**Comment by clayton33** [comment]
That work around solve my problem, thank you @cyrf0006 !

**Comment by joanpau** [comment]
@clayton33 I read that you succeeded building the mex file with `setupMexPosixtime`.
Can you confirm that the mex file is located in the same directory than the function `posixtime.m`?
If there is such a mex file in that directory, MATLAB should execute it instead of the .m file.
But from the error message MATLAB runs the .m file instead, which is quite puzzling.
For trial, after ensuring that the mex file is in the required directory,
you can just invoke `posixtime()` on the prompt and report the results
(no need to run the whole processing script).

**Comment by clayton33** [comment]
@joanpau sorry for the delayed response. 

Yes, the `mex` file in in the same directory as the function `posixtime.m`

Invoking `posixtime()` yields

```
>> posixtime()

ans =

   1.4860e+09
```

**Comment by joanpau** [comment]
@clayton33 So, in fact, after building the mex file with `setupPosixtime`, invoking `posixtime()` works as expected (I assume we are running the original code, not the workaround mentioned earlier).
Then, `generateOutputNetCDF()` should not throw the error message.

If it still does, the only reason I can think of is a conflict in the MATLAB path:
I guess that, at runtime, some script modifies the path and prepends it with a another directory containing the original `posixtime.m` file but not the mex file. Then MATLAB finds the m file first and invokes it.
Please note that the two main processing scripts **do** modify the path
to include the directory of the glider toolbox and its subdirectories (lines [171][1] and [186][2] respectively).
Those conflicts should become apparent in the output of `path()`
in the same session in which the main scripts have been executed.


  [1]: <https://github.com/socib/glider_toolbox/blob/master/m/main_glider_data_processing_dt.m#L171>
  [2]: <https://github.com/socib/glider_toolbox/blob/master/m/main_glider_data_processing_rt.m#L186>
